version: "3.9"

services:
  app:
    image: "auth_app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: pipenv run python -m main.app
    